"
"winpos 60 45
"set lines=62 columns=120

"set guifont=Lucida_Sans_Typewriter_Regular:h14
"set guifont=Bitstream\ Vera\ Sans\ Mono\ 12
set guifont=Consolas:h14

set encoding=utf-8
"set termencoding=macroman
"set nomacatsui
"set transparency=5
set antialias

set hlsearch
set guioptions-=T
set guioptions+=c
set noshowcmd " this causes performance problems

"colorscheme inkpot
"colorscheme midnight2
"colorscheme vividchalk
"colorscheme delek
"colorscheme railscasts
"colorscheme liquidcarbon
"colorscheme default
set background=dark
colorscheme solarized

" toggle search term highlighting -- handy when you want it,
" irritating and distracting when you don't.
nmap <D-u> :nohls<CR>

" Force this to work, even with rails plugin
nmap <silent> <D-{> :tabp<CR>
nmap <silent> <D-}> :tabn<CR>
nmap <silent> <D-w> :confirm close<CR>

nmap <silent> <D-t> :tabnew<CR>:CommandT<CR>

nmap <D-M> :Rake<CR>
nmap <M-D-M> :.Rake<CR>

