#!/usr/bin/env ruby

git_bundles = %w[ 
  git://github.com/astashov/vim-ruby-debugger.git
  git://github.com/kemiller/vim-ir_black.git
  git://github.com/msanders/snipmate.vim.git
  git://github.com/scrooloose/nerdtree.git
  git://github.com/timcharper/textile.vim.git
  git://github.com/tpope/vim-cucumber.git
  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-git.git
  git://github.com/tpope/vim-haml.git
  git://github.com/tpope/vim-markdown.git
  git://github.com/tpope/vim-pathogen.git
  git://github.com/tpope/vim-rails.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-surround.git
  git://github.com/tpope/vim-vividchalk.git
  git://github.com/tsaleh/vim-align.git
  git://github.com/tsaleh/vim-matchit.git
  git://github.com/tsaleh/vim-shoulda.git
  git://github.com/tsaleh/vim-supertab.git
  git://github.com/tsaleh/vim-tcomment.git
  git://github.com/vim-ruby/vim-ruby.git
  git://github.com/wincent/Command-T
  git://github.com/mattn/zencoding-vim.git
  git://github.com/juvenn/mustache.vim.git
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
  ["proton",        "2510",  "colors"],
  ["mayansmoke",    "3065",  "colors"]
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "  Unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

system "cd Command-T && PATH=/usr/bin rake make"
