"source $VIMRUNTIME/vimrc_example.vim

" General Settings
colorscheme default 
set background=light
set nohlsearch
set incsearch
set backupdir=~/.bak
set backup
set showmatch
set noexpandtab
set printoptions=portrait:n,paper:letter
set laststatus=2
set statusline=%t\ (%{GitBranch()})\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set wildignore=.git,vendor,.svn,*~,*.swp,*.swo
set switchbuf=usetab

filetype plugin indent on
syntax on

" netrw config
"
" Hide . .. and .svn
let g:netrw_list_hide='^\.\(svn\|\.\)\?/$'

" Persistent typos
iabbrev Parnter Partner
iabbrev parnter partner
iabbrev Paramter Parameter
iabbrev paramter parameter

" Key Bindings
nmap <C-TAB> :tabnext<cr>
nmap <C-S-TAB> :tabprev<cr>
imap <C-a> <ESC>gI
imap <C-e> <ESC>A

" Command-T bindings
map ,t :tabnew<CR>:CommandT<CR>
map ,e :CommandT<CR>

" Use tabs for opening files under the cursor
nmap gtf :tabe <cfile><CR>

" Macros

" Swap two items in a comma-separated list.  Needs some work
nmap _S /,<CR>bywdwwdw?,<CR>P/,<CR>l"0p

augroup misc
	" Make crontab -e work
	autocmd BufRead,BufNewFile /private/tmp/crontab.* set nowritebackup backupcopy=yes
	autocmd BufRead,BufNewFile *.rb set sw=2 ts=2 expandtab
	autocmd BufRead,BufNewFile *.rhtml set sw=2 ts=2 expandtab
	autocmd BufRead,BufNewFile *.yaml,*.yml set sw=2 ts=2 expandtab smartindent
	autocmd BufRead,BufNewFile *.viki set smartindent ft=viki
augroup END

" rails plugin settings
let g:rails_syntax=1
let g:rails_statusline=1

" These don't seem to work, but I'd like them to, so I'm leaving them around
autocmd User */.git/rebase-merge/git-rebase-todo nmap s ciwsquash<ESC>
autocmd User */.git/rebase-merge/git-rebase-todo nmap p ciwpick<ESC>
autocmd User */.git/rebase-merge/git-rebase-todo nmap e ciwedit<ESC>

augroup rails
	
	" remove any commands from this group so that we're starting fresh
	autocmd! 

	" Rails 'IDE' stuff
	autocmd User Rails command! -nargs=+ Desc :DBDescribeTable
	autocmd User Rails cmap ac<space> RTcontroller 
	autocmd User Rails cmap am<space> RTmodel 
	autocmd User Rails cmap av<space> RTview 
	autocmd User Rails cmap ah<space> RThelper 
	autocmd User Rails cmap tu<space> RTunittest 
	autocmd User Rails cmap tf<space> RTfunctionaltest 
	autocmd User Rails cmap fx<space> RTfixture 
	autocmd User Rails cmap mg<space> RTmigration 

	autocmd User ~/main/{core,crm,support}/* set path+=~/main/shared
	autocmd User ~/main/shared/* set path+=~/main/core
	autocmd User Rails.fixture* set sw=2 ts=8 et syntax=yaml
	autocmd User Gemfile set sw=2 ts=8 et
	autocmd User *.yml set sw=2 ts=8 et syntax=yaml
	autocmd User *.yaml set sw=2 ts=8 et syntax=yaml

	autocmd User Rails nmap <D-C> :Rake<CR>
	autocmd User Rails nmap <D-R> :Rake db:migrate:redo<CR>

augroup END



