"source $VIMRUNTIME/vimrc_example.vim

" General Settings
colorscheme default 
set background=light
set nohlsearch
set incsearch
set backupdir=~/.bak
set backup
set showmatch
set ts=4 sw=4
set noexpandtab
set printoptions=portrait:n,paper:letter
set laststatus=2
set statusline=%t\ (%{GitBranch()})\ %h%m%r%=%-14.(%l,%c%V%)\ %P

" Use tabs for opening files under the cursor
nmap gtf :tabe <cfile><CR>

filetype plugin indent on
syntax on

" netrw config
"
" Hide . .. and .svn
let g:netrw_list_hide='^\.\(svn\|\.\)\?/$'

" Persistent typos
iabbrev Parnter Partner
iabbrev parnter partner
iabbrev Paramter Parameter
iabbrev paramter parameter

" Key Bindings
nmap <C-TAB> :tabnext<cr>
nmap <C-S-TAB> :tabprev<cr>
nmap <C-a> ^
nmap <C-e> $
imap <C-a> <ESC>gI
imap <C-e> <ESC>A

map \t :FuzzyFinderTextMate<CR>

" Macros

" Swap two items in a comma-separated list.  Needs some work
nmap _S /,<CR>bywdwwdw?,<CR>P/,<CR>l"0p

augroup misc
	" Make crontab -e work
	autocmd BufRead,BufNewFile /private/tmp/crontab.* set nowritebackup backupcopy=yes
	autocmd BufRead,BufNewFile *.rhtml set sw=2 ts=2 expandtab
	autocmd BufRead,BufNewFile *.yaml,*.yml set sw=2 ts=2 expandtab smartindent
	autocmd BufRead,BufNewFile *.viki set smartindent ft=viki
augroup END

" rails plugin settings
let g:rails_syntax=1
let g:rails_statusline=1

augroup rails
	
	" remove any commands from this group so that we're starting fresh
	autocmd! 

	" Rails 'IDE' stuff
	autocmd User Rails command! -nargs=+ Desc :DBDescribeTable
	autocmd User Rails cmap ac<space> RTcontroller 
	autocmd User Rails cmap am<space> RTmodel 
	autocmd User Rails cmap av<space> RTview 
	autocmd User Rails cmap ah<space> RThelper 
	autocmd User Rails cmap tu<space> RTunittest 
	autocmd User Rails cmap tf<space> RTfunctionaltest 
	autocmd User Rails cmap fx<space> RTfixture 
	autocmd User Rails cmap mg<space> RTmigration 

	autocmd User ~/main/* set sw=4 ts=4 noet path+=~/main/shared
	autocmd User ~/main/shared/* set path+=~/main/core
	autocmd User Rails.fixture* set sw=2 ts=8 et syntax=yaml
	autocmd User Rails/config/*.yml set sw=2 ts=8 et syntax=yaml

	autocmd User Rails nmap <D-C> :Rake<CR>

augroup END



